runtime ./plugins.vim
runtime ./keymap.vim
runtime ./defx.vim
runtime ./settings.vim
runtime ./plugins/coc.vim
runtime ./plugins/nerdcommenter.vim
runtime ./plugins/denite.vim
runtime ./plugins/vim-illuminate.vim
runtime ./plugins/vim-xkbswitch.vim
